# Generated by Django 3.2.7 on 2021-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
